version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# Update WEBPASSWORD environment variable
# Might need to create the pihole and dnsmasq.d directories before issuing
# $ docker-compose up -d --build
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Toronto'
      WEBPASSWORD: '<INSERT PASSWORD HERE>'
    # Volumes store your data between container upgrades
    volumes:
       - './pihole/:/etc/pihole/'
       - './dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped